/* DICOL Rebates — demo local. Al publicar el Apps Script, configure window.DICOL_REBATES_API con su URL. */
const STORE = 'dicol.rebates.v1';
const defaultPolicy = { sales:{label:'PSI / ventas',weight:50,target:100}, demos:{label:'Demostraciones',weight:20,target:100}, parts:{label:'Repuestos',weight:10,target:100}, pilots:{label:'Pilotos certificados',weight:10,target:100}, information:{label:'Información y soportes',weight:10,target:100}, tiers:[{name:'A',min:80,rebate:5},{name:'B',min:60,rebate:3},{name:'C',min:0,rebate:0}] };
const sample = { policy:defaultPolicy, specialists:[{id:'sp-1',name:'Manuel Alejandro Chavarro Arteaga',zone:'Centro'},{id:'sp-2',name:'Especialista sin asignar',zone:'—'}], partners:[{id:'pa-1',name:'Helidrones',specialistId:'sp-1',zone:'Bogotá',notes:'Validar aplicación del rebate del trimestre anterior.',quarters:{Q1:{sales:90,demos:100,parts:80,pilots:100,information:100},Q2:{sales:65,demos:70,parts:100,pilots:50,information:100},Q3:{},Q4:{}}},{id:'pa-2',name:'Innova Dron',specialistId:'sp-1',zone:'Centro',notes:'Seguimiento de demostraciones requerido.',quarters:{Q1:{sales:65,demos:40,parts:100,pilots:40,information:100},Q2:{sales:55,demos:50,parts:60,pilots:0,information:100},Q3:{},Q4:{}}},{id:'pa-3',name:'Mapagro',specialistId:'sp-1',zone:'Norte',notes:'Aliado con alto volumen; revisar evidencia antes de liquidar.',quarters:{Q1:{sales:100,demos:100,parts:90,pilots:100,information:100},Q2:{sales:72,demos:80,parts:60,pilots:70,information:100},Q3:{},Q4:{}}}] };
let state = JSON.parse(localStorage.getItem(STORE) || 'null') || sample; let selectedId = state.partners[0]?.id; const $=s=>document.querySelector(s);
const quarter=()=>$('#quarterFilter').value; const partner=()=>state.partners.find(p=>p.id===selectedId); const specialist=id=>state.specialists.find(s=>s.id===id);
function persist(){localStorage.setItem(STORE,JSON.stringify(state));}
function evalPartner(p,q=quarter()){const data=p.quarters[q]||{};let score=0;Object.entries(state.policy).filter(([k])=>k!=='tiers').forEach(([key,item])=>score+=(Math.min(100,Number(data[key]||0))/100)*item.weight); score=Math.round(score);const tier=state.policy.tiers.find(t=>score>=t.min)||state.policy.tiers.at(-1);return{score,tier,data};}
function render(){renderMetrics();renderList();renderDetail();}
function renderMetrics(){const list=state.partners.map(p=>evalPartner(p));const avg=list.length?Math.round(list.reduce((s,x)=>s+x.score,0)/list.length):0;$('#partnerCount').textContent=list.length;$('#partnerCountDetail').textContent=`${state.specialists.length} especialista(s) registrado(s)`;$('#averageScore').textContent=`${avg}%`;$('#projectedRebate').textContent=`${list.length?(list.reduce((s,x)=>s+x.tier.rebate,0)/list.length).toFixed(1):0}%`;$('#atRiskCount').textContent=list.filter(x=>x.score<60).length;}
function renderList(){const term=$('#partnerSearch').value.toLowerCase();$('#partnerList').innerHTML=state.partners.filter(p=>p.name.toLowerCase().includes(term)).map(p=>{const e=evalPartner(p), sp=specialist(p.specialistId);return `<button class="partner-item ${p.id===selectedId?'active':''}" data-id="${p.id}"><span class="partner-avatar">${p.name.slice(0,2).toUpperCase()}</span><span><strong>${esc(p.name)}</strong><small>${esc(sp?.name||'Sin especialista')} · ${e.score}% · ${e.tier.name}</small></span></button>`}).join('')||'<p class="empty-state">No hay aliados.</p>';document.querySelectorAll('.partner-item').forEach(x=>x.onclick=()=>{selectedId=x.dataset.id;render();});}
function renderDetail(){const p=partner();$('#emptyState').hidden=!!p;$('#detailContent').hidden=!p;if(!p)return;const r=evalPartner(p),sp=specialist(p.specialistId);$('#detailName').textContent=p.name;$('#detailSpecialist').textContent=sp?`RESPONSABLE · ${sp.name.toUpperCase()}`:'SIN ESPECIALISTA';$('#detailContext').textContent=[p.zone,p.notes].filter(Boolean).join(' · ');$('#scoreValue').textContent=`${r.score}%`;$('#scoreGrade').textContent=`NIVEL ${r.tier.name}`;document.querySelector('.score-ring').style.setProperty('--score',`${r.score}%`);$('#scoreExplanation').textContent=r.score>=80?'El aliado cumple la meta de nivel A para este periodo.':r.score>=60?'El aliado alcanza el nivel B; hay oportunidad de elevar el resultado.':'El aliado está por debajo del mínimo de cumplimiento.';$('#gradeName').textContent=`Nivel ${r.tier.name}`;$('#rebateValue').textContent=`${r.tier.rebate}% de rebate proyectado`;$('#policyNote').textContent=`Ponderación activa: ${Object.values(state.policy).filter(x=>x?.weight).map(x=>`${x.label} ${x.weight}%`).join(' · ')}.`;renderIndicators(r);renderTrend(p);renderInsights(r);}
function renderIndicators(r){$('#indicatorGrid').innerHTML=Object.entries(state.policy).filter(([k])=>k!=='tiers').map(([key,x])=>{let v=Number(r.data[key]||0);return `<article class="indicator"><label>${esc(x.label)} <output>${v}%</output></label><small>Peso ${x.weight}% · meta ${x.target}%</small><input data-key="${key}" type="range" min="0" max="100" value="${v}"><progress value="${v}" max="100"></progress></article>`}).join('');document.querySelectorAll('.indicator input').forEach(input=>input.oninput=()=>{input.parentElement.querySelector('output').textContent=`${input.value}%`;input.parentElement.querySelector('progress').value=input.value;});}
function renderTrend(p){$('#trendChart').innerHTML=['Q1','Q2','Q3','Q4'].map(q=>{const x=evalPartner(p,q).score;return `<div class="bar" style="height:${Math.max(x,5)}%"><span>${x}%</span></div>`}).join('');}
function renderInsights(r){const weak=Object.entries(state.policy).filter(([k])=>k!=='tiers'&&Number(r.data[k]||0)<state.policy[k].target).sort((a,b)=>Number(r.data[a[0]]||0)-Number(r.data[b[0]]||0));$('#statusTitle').textContent=r.score>=80?'Cumple y es elegible para el nivel superior.':r.score>=60?'Cumple parcialmente: puede mejorar su clasificación.':'No está cumpliendo la meta trimestral.';$('#statusText').textContent=r.score>=80?'Mantenga evidencias, valide las condiciones comerciales aplicables y confirme la liquidación del periodo siguiente.':'La recomendación se calcula con los indicadores activos; la liquidación requiere validar soportes y condiciones de la política.';$('#priorityActions').innerHTML=(weak.length?weak.slice(0,3).map(([_,x])=>`<li>Priorizar <b>${esc(x.label)}</b> para cerrar la brecha del trimestre.</li>`):['<li>Todos los indicadores están en su meta. Validar los soportes antes de liquidar.</li>']).join('');}
function openPartner(p){$('#partnerDialogTitle').textContent=p?'Editar aliado':'Nuevo aliado';$('#partnerId').value=p?.id||'';$('#partnerName').value=p?.name||'';$('#partnerZone').value=p?.zone||'';$('#partnerNotes').value=p?.notes||'';$('#partnerSpecialist').innerHTML=state.specialists.map(s=>`<option value="${s.id}" ${p?.specialistId===s.id?'selected':''}>${esc(s.name)}${s.zone?' — '+esc(s.zone):''}</option>`).join('');$('#partnerDialog').showModal();}
$('#newPartnerButton').onclick=()=>openPartner();$('#editPartnerButton').onclick=()=>openPartner(partner());$('#partnerForm').addEventListener('submit',e=>{if(e.submitter?.value==='cancel')return;e.preventDefault();const id=$('#partnerId').value||`pa-${Date.now()}`, old=state.partners.find(p=>p.id===id);const p={id,name:$('#partnerName').value.trim(),specialistId:$('#partnerSpecialist').value,zone:$('#partnerZone').value.trim(),notes:$('#partnerNotes').value.trim(),quarters:old?.quarters||{}};if(!p.name)return;state.partners=old?state.partners.map(x=>x.id===id?p:x):[p,...state.partners];selectedId=id;persist();$('#partnerDialog').close();render();});
$('#newSpecialistButton').onclick=()=>$('#specialistDialog').showModal();$('#specialistForm').addEventListener('submit',e=>{if(e.submitter?.value==='cancel')return;e.preventDefault();const name=$('#specialistName').value.trim();if(!name)return;state.specialists.push({id:`sp-${Date.now()}`,name,zone:$('#specialistZone').value.trim()});persist();$('#specialistDialog').close();render();});
$('#saveIndicatorsButton').onclick=()=>{const p=partner(),q=quarter();p.quarters[q]=p.quarters[q]||{};document.querySelectorAll('.indicator input').forEach(x=>p.quarters[q][x.dataset.key]=Number(x.value));persist();render();};$('#deletePartnerButton').onclick=()=>{if(partner()&&confirm(`¿Eliminar a ${partner().name}?`)){state.partners=state.partners.filter(x=>x.id!==selectedId);selectedId=state.partners[0]?.id;persist();render();}};
$('#partnerSearch').oninput=renderList;$('#quarterFilter').onchange=render;$('#settingsButton').onclick=()=>{const fields=Object.entries(state.policy).filter(([k])=>k!=='tiers').map(([key,x])=>`<label>${esc(x.label)} · peso (%)<input type="number" min="0" max="100" name="${key}" value="${x.weight}"></label>`).join('');$('#policyFields').innerHTML=fields;$('#policyDialog').showModal();};$('#policyForm').addEventListener('submit',e=>{if(e.submitter?.value==='cancel')return;e.preventDefault();Object.keys(state.policy).filter(k=>k!=='tiers').forEach(k=>state.policy[k].weight=Number(e.target.elements[k].value)||0);persist();$('#policyDialog').close();render();});document.querySelectorAll('[data-close]').forEach(button=>button.onclick=()=>document.querySelector(`#${button.dataset.close}`).close());function esc(v){return String(v??'').replace(/[&<>'"]/g,x=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[x]));}render();
