/**
 * LEGALIZACIONES DE GASTOS — proyecto Apps Script independiente.
 * Cree una hoja de cálculo nueva con este nombre, pegue este archivo y despliegue
 * como aplicación web. No mezcle este código con Code.gs (rebates).
 *
 * Propiedades del script obligatorias:
 * FIREBASE_WEB_API_KEY  API key web del mismo proyecto Firebase.
 * GITHUB_OWNER           organización/usuario GitHub.
 * GITHUB_REPO            repositorio de facturas (privado recomendado).
 * GITHUB_BRANCH          rama, por ejemplo main.
 * GITHUB_TOKEN           fine-grained PAT con Contents: Read and write SOLO en ese repo.
 */
const LG = { expenses: 'Salidas', expenseHeaders: ['id','especialista_id','nombre','responsable','identificacion','cargo','centro_costo','ruta','tipo','anticipo','fecha','destino','estado','observaciones','hoja','creado_en','actualizado_en'], invoiceHeaders: ['id','fecha','numero','nit','proveedor','pago','concepto','descripcion','valor','cufe','support_url','support_path','support_kind','receipt_url','receipt_path'] };
function setupLegalizaciones() { ensureLgSheet_(LG.expenses, LG.expenseHeaders); }
function doGet() { return lgResponse_({ ok:false, error:'Use POST autenticado.' }); }
function doPost(e) { let request={}; try { request=JSON.parse(e.postData.contents||'{}'); return lgResponse_({ok:true,data:lgDispatch_(request)}); } catch (error) { console.error(error.stack||error); return lgResponse_({ok:false,error:error.message||'Error inesperado.'}); } }
function lgDispatch_(r) { const session=lgSession_(r.idToken); const data=r.data||{}; switch(r.action) { case 'listExpenses': return {expenses:lgList_(session)}; case 'saveExpense': return lgSaveExpense_(session,data); case 'saveInvoice': return lgSaveInvoice_(session,data); case 'uploadSupport': return lgUpload_(session,data); case 'downloadSupport': return lgDownload_(session,data); case 'deleteInvoice': return lgDeleteInvoice_(session,data); case 'deleteExpense': return lgDeleteExpense_(session,r.id); case 'finalizeExpense': return lgDeleteExpense_(session,r.id); default: throw new Error('Acción no permitida.'); } }
function lgSession_(idToken) { if(!idToken) throw new Error('Sesión requerida.'); const key=PropertiesService.getScriptProperties().getProperty('FIREBASE_WEB_API_KEY'); if(!key) throw new Error('Configure FIREBASE_WEB_API_KEY.'); const response=UrlFetchApp.fetch('https://identitytoolkit.googleapis.com/v1/accounts:lookup?key='+encodeURIComponent(key),{method:'post',contentType:'application/json',payload:JSON.stringify({idToken:idToken}),muteHttpExceptions:true}); const payload=JSON.parse(response.getContentText()||'{}'); const user=payload.users&&payload.users[0]; if(response.getResponseCode()!==200||!user||user.disabled) throw new Error('Sesión Firebase no válida.'); const claims=JSON.parse(user.customAttributes||'{}'); if(['admin','specialist'].indexOf(claims.role)<0) throw new Error('Perfil no autorizado.'); if(claims.role==='specialist'&&!claims.specialistId) throw new Error('El usuario no tiene ID de especialista.'); return {uid:user.localId,role:claims.role,specialistId:claims.specialistId||''}; }
function lgList_(session) { return lgRows_(LG.expenses).filter(function(row){return session.role==='admin'||row.especialista_id===session.specialistId;}).map(function(row){ return Object.assign(lgExpenseOut_(row),{invoices:lgInvoices_(row)}); }); }
function lgSaveExpense_(session,d) { if(!d.id||!d.name) throw new Error('La salida debe tener ID y nombre.'); const old=lgById_(d.id); if(old) lgAuthorize_(session,old); const owner=session.role==='admin' ? (old?old.especialista_id:(d.specialistId||session.uid)) : session.specialistId; const row={id:d.id,especialista_id:owner,nombre:d.name,responsable:d.owner||'',identificacion:d.identification||'',cargo:d.role||'',centro_costo:d.costCenter||'',ruta:d.route||'',tipo:d.legalizationType||'',anticipo:Number(d.advance||0),fecha:d.date||'',destino:d.destination||'',estado:d.status||'Pendiente',observaciones:d.notes||'',hoja:old?old.hoja:lgSheetName_(d.id),creado_en:old?old.creado_en:new Date().toISOString(),actualizado_en:new Date().toISOString()}; lgUpsert_(LG.expenses,LG.expenseHeaders,row); lgEnsureInvoiceSheet_(row.hoja); return lgExpenseOut_(row); }
function lgSaveInvoice_(session,d) { const expense=lgById_(d.expenseId); lgAuthorize_(session,expense); const invoice=d.invoice||{}; if(!invoice.id) throw new Error('Factura sin ID.'); const sheet=lgEnsureInvoiceSheet_(expense.hoja); const row={id:invoice.id,fecha:invoice.date||'',numero:invoice.number||'',nit:invoice.nit||'',proveedor:invoice.supplier||'',pago:invoice.payment||'',concepto:invoice.concept||'',descripcion:invoice.description||'',valor:Number(invoice.amount||0),cufe:invoice.cufe||'',support_url:invoice.supportUrl||'',support_path:invoice.supportPath||'',support_kind:invoice.supportKind||'',receipt_url:invoice.receiptUrl||'',receipt_path:invoice.receiptPath||''}; lgUpsertSheet_(sheet,LG.invoiceHeaders,row); return lgInvoiceOut_(row); }
function lgUpload_(session,d) { const expense=lgById_(d.expenseId); lgAuthorize_(session,expense); if(!d.base64||!d.invoiceId) throw new Error('Archivo incompleto.'); const bytes=Utilities.base64Decode(d.base64); if(bytes.length>10*1024*1024) throw new Error('El archivo supera 10 MB.'); const safe=String(d.fileName||'soporte').replace(/[^a-zA-Z0-9._-]/g,'_'); const path='Facturas/'+expense.especialista_id+'/'+expense.id+'/'+d.invoiceId+'/'+d.kind+'_'+safe; const url=lgGitHubPut_(path,d.base64,d.mimeType||'application/octet-stream'); return {url:url,path:path}; }
function lgDownload_(session,d) { const expense=lgById_(d.expenseId || (String(d.path||'').split('/')[2] || '')); lgAuthorize_(session,expense); const c=lgGitHubConfig_(), endpoint='https://api.github.com/repos/'+c.owner+'/'+c.repo+'/contents/'+encodeURIComponent(d.path).replace(/%2F/g,'/')+'?ref='+encodeURIComponent(c.branch); const response=UrlFetchApp.fetch(endpoint,{headers:{Authorization:'Bearer '+c.token,Accept:'application/vnd.github+json','User-Agent':'DICOL-Legalizaciones'},muteHttpExceptions:true}); if(response.getResponseCode()!==200) throw new Error('No se pudo leer el soporte desde GitHub.'); return {base64:JSON.parse(response.getContentText()).content.replace(/\n/g,'')}; }
function lgDeleteInvoice_(session,d) { const expense=lgById_(d.expenseId); lgAuthorize_(session,expense); const sheet=lgEnsureInvoiceSheet_(expense.hoja); const row=lgRowsFromSheet_(sheet).filter(function(x){return x.id===d.invoiceId;})[0]; if(!row) return {deleted:false}; [row.support_path,row.receipt_path].filter(String).forEach(lgGitHubDelete_); lgDeleteRow_(sheet,'id',d.invoiceId); return {deleted:true}; }
function lgDeleteExpense_(session,id) { const expense=lgById_(id); lgAuthorize_(session,expense); lgInvoices_(expense).forEach(function(invoice){ [invoice.support_path,invoice.receipt_path].filter(String).forEach(lgGitHubDelete_); }); const ss=SpreadsheetApp.getActive(); const tab=ss.getSheetByName(expense.hoja); if(tab) ss.deleteSheet(tab); lgDeleteRow_(ensureLgSheet_(LG.expenses,LG.expenseHeaders),'id',id); return {deleted:true}; }
function lgAuthorize_(session,expense) { if(!expense) throw new Error('Salida no encontrada.'); if(session.role!=='admin'&&expense.especialista_id!==session.specialistId) throw new Error('No puedes acceder a esta salida.'); }
function lgInvoices_(expense) { const sheet=SpreadsheetApp.getActive().getSheetByName(expense.hoja); return sheet?lgRowsFromSheet_(sheet).map(lgInvoiceOut_):[]; }
function lgExpenseOut_(r){return {id:r.id,name:r.nombre,owner:r.responsable,identification:r.identificacion,role:r.cargo,costCenter:r.centro_costo,route:r.ruta,legalizationType:r.tipo,advance:Number(r.anticipo||0),date:r.fecha,destination:r.destino,status:r.estado,notes:r.observaciones};}
function lgInvoiceOut_(r){return {id:r.id,date:r.fecha,number:r.numero,nit:r.nit,supplier:r.proveedor,payment:r.pago,concept:r.concepto,description:r.descripcion,amount:Number(r.valor||0),cufe:r.cufe,supportUrl:r.support_url,supportPath:r.support_path,supportKind:r.support_kind,receiptUrl:r.receipt_url,receiptPath:r.receipt_path};}
function lgSheetName_(id){return 'SAL_'+String(id).replace(/[^A-Za-z0-9]/g,'').slice(-60);}
function ensureLgSheet_(name,headers){const ss=SpreadsheetApp.getActive();let sheet=ss.getSheetByName(name);if(!sheet){sheet=ss.insertSheet(name);sheet.getRange(1,1,1,headers.length).setValues([headers]);sheet.setFrozenRows(1);}return sheet;}
function lgEnsureInvoiceSheet_(name){return ensureLgSheet_(name,LG.invoiceHeaders);}
function lgRows_(name){return lgRowsFromSheet_(ensureLgSheet_(name,LG.expenseHeaders));}
function lgRowsFromSheet_(sheet){const range=sheet.getDataRange().getValues();if(range.length<2)return [];const headers=range[0];return range.slice(1).filter(r=>r[0]!=='').map(r=>headers.reduce((o,h,i)=>(o[h]=r[i],o),{}));}
function lgById_(id){return lgRows_(LG.expenses).filter(r=>r.id===id)[0];}
function lgUpsert_(name,headers,row){lgUpsertSheet_(ensureLgSheet_(name,headers),headers,row);}
function lgUpsertSheet_(sheet,headers,row){const values=headers.map(h=>row[h]===undefined?'':row[h]);const rows=lgRowsFromSheet_(sheet);const index=rows.findIndex(r=>r.id===row.id);if(index>=0)sheet.getRange(index+2,1,1,headers.length).setValues([values]);else sheet.appendRow(values);}
function lgDeleteRow_(sheet,column,id){const headers=sheet.getRange(1,1,1,sheet.getLastColumn()).getValues()[0];const col=headers.indexOf(column)+1;if(!col)return;const values=sheet.getRange(2,col,Math.max(sheet.getLastRow()-1,1),1).getValues();const index=values.findIndex(r=>r[0]===id);if(index>=0)sheet.deleteRow(index+2);}
function lgGitHubConfig_(){const p=PropertiesService.getScriptProperties();const owner=p.getProperty('GITHUB_OWNER'),repo=p.getProperty('GITHUB_REPO'),branch=p.getProperty('GITHUB_BRANCH')||'main',token=p.getProperty('GITHUB_TOKEN');if(!owner||!repo||!token)throw new Error('Configure GITHUB_OWNER, GITHUB_REPO y GITHUB_TOKEN en Propiedades del script.');return {owner:owner,repo:repo,branch:branch,token:token};}
function lgGitHubPut_(path,base64,mime){const c=lgGitHubConfig_(),endpoint='https://api.github.com/repos/'+c.owner+'/'+c.repo+'/contents/'+encodeURIComponent(path).replace(/%2F/g,'/');const response=UrlFetchApp.fetch(endpoint,{method:'put',contentType:'application/json',headers:{Authorization:'Bearer '+c.token,Accept:'application/vnd.github+json','User-Agent':'DICOL-Legalizaciones'},payload:JSON.stringify({message:'Factura '+path,content:base64,branch:c.branch}),muteHttpExceptions:true});if(response.getResponseCode()<200||response.getResponseCode()>299)throw new Error('GitHub rechazó el archivo: '+response.getContentText());const body=JSON.parse(response.getContentText());return body.content.download_url;}
function lgGitHubDelete_(path){const c=lgGitHubConfig_(),endpoint='https://api.github.com/repos/'+c.owner+'/'+c.repo+'/contents/'+encodeURIComponent(path).replace(/%2F/g,'/');const old=UrlFetchApp.fetch(endpoint+'?ref='+encodeURIComponent(c.branch),{headers:{Authorization:'Bearer '+c.token,Accept:'application/vnd.github+json','User-Agent':'DICOL-Legalizaciones'},muteHttpExceptions:true});if(old.getResponseCode()===404)return;if(old.getResponseCode()!==200)throw new Error('No se pudo localizar archivo GitHub.');const sha=JSON.parse(old.getContentText()).sha;const response=UrlFetchApp.fetch(endpoint,{method:'delete',contentType:'application/json',headers:{Authorization:'Bearer '+c.token,Accept:'application/vnd.github+json','User-Agent':'DICOL-Legalizaciones'},payload:JSON.stringify({message:'Eliminar salida '+path,sha:sha,branch:c.branch}),muteHttpExceptions:true});if(response.getResponseCode()<200||response.getResponseCode()>299)throw new Error('No se pudo borrar archivo GitHub.');}
function lgResponse_(payload){return ContentService.createTextOutput(JSON.stringify(payload)).setMimeType(ContentService.MimeType.JSON);}
